<?php if ($this->getMethod()->getMailingAddress() || $this->getMethod()->getPayableTo()): ?>
    <ul class="form-list checkmo-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <?php if ($this->getMethod()->getPayableTo()): ?>
        <li>
            <label><?php echo $this->__('Make Check payable to:') ?></label>
            <?php echo $this->getMethod()->getPayableTo() ?>
        </li>
        <?php endif; ?>
        <?php if ($this->getMethod()->getMailingAddress()): ?>
        <li>
            <label><?php echo Mage::helper('payment')->__('Send to:') ?></label>
           <address class="checkmo-mailing-address">
                <?php echo nl2br($this->getMethod()->getMailingAddress());?>
                <?php $_SESSION['receiver']=nl2br($this->getMethod()->getMailingAddress());?>
              <?php $_SESSION['nganluong']=$this->getMethod()->getCheckout();?>
                <?php $_SESSION['merchantID']=nl2br($this->getMethod()->getMerchantSite());?>
             <?php     $_SESSION['mabaomat']=nl2br($this->getMethod()->getSecureCode());  ?>
                <?php $_SESSION['return_url']=nl2br($this->getMethod()->getReturnUrl());?>
            </address>
        </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>
